spring:
  datasource:
    url: jdbc:mysql://123.206.82.234:3306/permission?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

shiro:
  # token有效期，单位秒
  jwtTimeOut: 3600
server:
  port: 8080
